# Generated by Django 3.0.4 on 2020-08-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tables', models.BooleanField(default=False)),
                ('is_classification', models.BooleanField(default=False)),
                ('is_object', models.BooleanField(default=False)),
                ('is_face', models.BooleanField(default=False)),
                ('is_api', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('project_id', models.CharField(max_length=72)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
