# Generated by Django 3.0.4 on 2020-08-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200823_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='trained',
        ),
    ]
